import { MonthwisecertAuthDetailComponent } from "src/app/components/enggsys/managementreports/monthwisecert-auth-detail/monthwisecert-auth-detail.component";

export const fileConstants = {
    depositDetail: "FD_DepostDetailsForIT.rpt",
    interestDetail:"FD_InterestDetailsForIT.rpt",
    activeDepositIndividual:"FD_ActiveDepositsIndividual.rpt",
    activeDepositJointOwner:"FD_ActiveDepositsIndividualJHNomiDet.rpt",
    yearlyInterestDetails:"FD_DepositorTDSDetail.rpt",
    renewalReminderLetterNew:"RenewalReminderRpt_new.rpt",
    coveringLetter:"FD_Maturity_Renewal_letter.rpt",
    depositorInterestDetail:"FD_DepositorIntDetails.rpt",
    neftBankAdvicePnb:"FD_NEFT_IOB.rpt",
    neftBankAdviceOther:"FD_NEFT_Other.rpt",
    neftBankLetter:"FD_NEFT_Letter.rpt",
    depositReports:"Deposit.rpt",
    totalInterestPaidForAllDepositors: "FD_TotInterestPaidTillDate1.rpt",
    depositReportWithOutGrp:"DepositWithOutGrp.rpt",
    mailingDepositorAndBroker: "FrmMailingList.rpt",
    prematurDepositLists: "PrematureDeposit.rpt",
    listOfMonthwiseRepayments: "LstMthWiseRepay.rpt",
    PromiseRejectedMaturitiesReport:"ProjectedMaturity.rpt",
    activeDepositList: "ActiveDeposit.rpt",
    interestPaymentRegister: "IntPayReg.rpt",
    InterestChequePrint:"IntCheqPrintRpt.rpt",
    InterestChequeFolioPrint:"IntChqFolioPrint.rpt",
    // fixedDepositReceiptPrint: "Deposit Receipt.rpt",
    fixedDepositReceiptPrint: "DepositReceiptJava.rpt",
    outstandingDeposit: "OutstandingDeposit.rpt",
    listOfTotalDepAmnt: "LstDepWithTotAmt.rpt",
    listOfDepWithTax: "LstDepHavingTax(TaxAppl).rpt",
    PurchaseBillChallanReport: "Purchase_Challanrpt.rpt",
    supplierDetailsReport: "Mat_SupplierDetailsReport.rpt",
    companyWisePurchase: "CoyWisePurchase.rpt",
    vehicleWorkCodeWise: "AEVERPWW.rpt",
    matCodeMatWiseBilledQty: "MatgroupMatcodewiseBilledQty.rpt",
    matCodeMatWiseBilledQtyDet: "MatgroupMatcodewiseBilledQtyDet.rpt",
    chequeWiseBills: "ChequewiseBillsReport.rpt",
    vehicleExpenseDetail: "AEVEDTRP.rpt",
    vehicleHistory: "AEVEVHRP_Java.rpt",
    vehicleInsTaxExpiryDate: "AEVEVITERP.rpt",
    VehMthDetExpRep : "VehMonthwiseRpt.rpt",
    admRPinsuranceMaturingPolicyToDay:"Adm_RP_insurance_MaturingPolicy_ToDay.rpt",
    policymaturinguptotoday:"Adm_RP_insurance_MaturingPolicy.rpt",
    halfYrInterestLetter: "FD_InterestDeposit_letter.rpt",
    LsReceipt: "LsReceipt.rpt",
    LsVoucher: "LsVoucher.rpt",
    
}

